WebApplication3/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AceJobAgency.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password does not match")]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

WebApplication3/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace AceJobAgency.ViewModels
{
    public class Register
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string Gender { get; set; }

        [Required]
        public string NRIC { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public string BirthDate {  get; set; }

        [Required]
        //[RegularExpression(@"^.*\.(docx|pdf)$", ErrorMessage = "Invalid file format. Only .docx and .pdf are allowed.")]
        public string Resume {  get; set; }

        [Required]
        public string WhoAmI { get; set; }

        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{12,}$",
            ErrorMessage = "Password must be at least 12 characters long and include at least one lowercase letter, one uppercase letter, one number, and one special character.")]
        public string CustomValidationForPassword => Password;


    }
}

WebApplication3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AceJobAgency.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
	[Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApplication3/Pages/Login.cshtml.cs
//using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AceJobAgency.ViewModels;
using IdentityUser = Microsoft.AspNetCore.Identity.IdentityUser;

namespace AceJobAgency.Pages
{
    public class LoginModel : PageModel
    {
		[BindProperty]
		public Login LModel { get; set; }

		private readonly SignInManager<IdentityUser> signInManager;
		public LoginModel(SignInManager<IdentityUser> signInManager)
		{
			this.signInManager = signInManager;
		}
		public void OnGet()
        {
        }

		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
			   LModel.RememberMe, false);
				if (identityResult.Succeeded)
				{
					return RedirectToPage("Index", "Home");
				}
				//ModelState.AddModelError("", "Username or Password incorrect");
			}
			else
			{
                ModelState.AddModelError("", "Username or Password incorrect");
            }

			return Page();
		}
	}
}

WebApplication3/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class LogoutModel : PageModel
    {
		private readonly SignInManager<IdentityUser> signInManager;
		public LogoutModel(SignInManager<IdentityUser> signInManager)
		{
			this.signInManager = signInManager;
		}
		public void OnGet() { }
		public async Task<IActionResult> OnPostLogoutAsync()
		{
			await signInManager.SignOutAsync();
			return RedirectToPage("Login");
		}
		public async Task<IActionResult> OnPostDontLogoutAsync()
		{
			return RedirectToPage("Index");
		}
	}
}

WebApplication3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AceJobAgency.ViewModels;

namespace AceJobAgency.Pages
{
    public class RegisterModel : PageModel
    {

        private UserManager<IdentityUser> userManager { get; }
        private SignInManager<IdentityUser> signInManager { get; }

        [BindProperty]
        public Register RModel { get; set; }

        public RegisterModel(UserManager<IdentityUser> userManager,
        SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }



        public void OnGet()
        {
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                // Check if the email address is already in use
                var existingUser = await userManager.FindByEmailAsync(RModel.Email);
                if (existingUser != null)
                {
                    ModelState.AddModelError("", "Email address is already in use.");
                    return Page();
                }

                var user = new IdentityUser()
                {
                    UserName = RModel.Email,
                    Email = RModel.Email
                };
                var result = await userManager.CreateAsync(user, RModel.Password);

                // Hash the password before storing it
                //var hashedPassword = userManager.PasswordHasher.HashPassword(user, RModel.Password);
                //user.PasswordHash = hashedPassword;

                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, false);
                    //Redirect to home page
                    return RedirectToPage("Index", "Home");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();
        }







    }
}

WebApplication3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication3/Pages/Login.cshtml
@page
@model AceJobAgency.Pages.LoginModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post">

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>
			</form>
		</div>
	</div>
</div>

WebApplication3/Pages/Logout.cshtml
@page
@model AceJobAgency.Pages.LogoutModel
@{
}
<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

WebApplication3/Pages/Register.cshtml
@page
@model AceJobAgency.Pages.RegisterModel
@{
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
                    <label class="form-label" asp-for="RModel.FirstName">First Name</label>
                    <input type="text" asp-for="RModel.FirstName" class="form-control" />
                    <span asp-validation-for="RModel.FirstName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.LastName">Last Name</label>
                    <input type="text" asp-for="RModel.LastName" class="form-control" />
                    <span asp-validation-for="RModel.LastName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Gender">Gender</label>
                    <input type="text" asp-for="RModel.Gender" class="form-control" />
                    <span asp-validation-for="RModel.Gender" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.NRIC">NRIC</label>
                    <input type="text" asp-for="RModel.NRIC" class="form-control" />
                    <span asp-validation-for="RModel.NRIC" class="text-danger"></span>
                </div>


				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Email">Email Address</label>
					<input type="Text" asp-for="RModel.Email" class="form-control" />
					<span asp-validaton-for="RModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Password">Password</label>
                    <input type="password" asp-for="RModel.Password" class="form-control" />
					<span asp-validaton-for="RModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="RModel.ConfirmPassword" class="form-control" />
					<span asp-validaton-for="RModel.ConfirmPassword" class="text-danger"></span>
				</div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.BirthDate">Birth Date</label>
                    <input type="date" asp-for="RModel.BirthDate" class="form-control" />
                    <span asp-validation-for="RModel.BirthDate" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Resume">Resume</label>
                    <textarea asp-for="RModel.Resume" class="form-control"></textarea>
                    <span asp-validation-for="RModel.Resume" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.WhoAmI">Who Am I</label>
                    <textarea asp-for="RModel.WhoAmI" class="form-control"></textarea>
                    <span asp-validation-for="RModel.WhoAmI" class="text-danger"></span>
                </div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>